[package]
name = "dash-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.31", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.47"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
json_comments = "0.2.2"
