[package]
name = "gdml-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-xid = "0.2.4"
strum = { version = "0.25.0", features = ["derive"] }
gdml-macros = { path = "macros" }
paste = "1.0.14"
