[package]
name = "geo-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.31", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.47"
unicode-xid = "0.2.4"
convert_case = "0.6.0"
